### ISSUE TITLE
[feature request]: Add option to use PostgreSQL without High Availability

### ISSUE THREAD

**Issue by KlausThornProgrammfabrik** [programmfabrik/fylr-helm#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

During the last days, fylr instances stopped responding due to `Unable to connect to database: pq: pgpool is not accepting any new connections`. Restart of the HA Postgres solved it.

We are not using High Availability, so it has more disadvantages than advantages for us.

### Describe the solution you'd like:

Please implement the helm chart to have Postgres without added replicas or other complications. Maybe Postgres from the Postgres developers would be best.

### Describe alternatives you've considered

We considered removing the HA postgres completely form the Helm chart but we have one customer who maybe is using this. They did not answer our inquiry yet. If you need to know whether you can remove HA, then we can press the issue there.

### Additional context:

TODO:
- DAM United: estimate cost for this change
- Programmfabrik: decide whether or not to do it for that price

**Comment by jhoenow-du** [comment]
We assume an effort of 5h.

**Comment by sebastianklarmann** [comment]
> We assume an effort of 5h.
Please implement.

**Comment by KlausThornProgrammfabrik** [comment]
After a meeting  with Jens-Thomas Hönow and Programmfabrik's customer Uni-Münster, it is now clear
* the current Postgres H.A.-Solution (bitnami I guess) shall be abandoned in favor of probably Patroni
* Postgrs without H.A. is interesting for instances where no H.A. is required

**Comment by KlausThornProgrammfabrik** [comment]
Thanks for notifying me via chat! But I guess so that others can follow here ( like: what step next, who is doing it etc.), please write into the issue.

So to recapitulate:
* Me and @jhoenow-du had a look at the changes and they seem fine to us.
* I suggested that @haziz-du does the merge himself, as it involves building a release and thus is strongly connected to the changes and how they interact with the release-building automatisms.
* I suggest that @haziz-du does the rollout in the cloud so that we can all benefit from the changes
* @haziz-du already asked chatted with @mad-pf about migrating from the postgres HA to normal postrgres in the cloud

(but the cloud is a separat topic with a separate -private- repository. So I guess it would be strange to go into detail about the cloud here)

**Comment by haziz-du** [comment]
No, the only dependency required and used is the postgresql chart, you can find the list of dependencies in the chart.yaml file

**Comment by KlausThornProgrammfabrik** [comment]
I was just surprised that suddenly, bitnami/cilium is appearing in our repository. It was after you worked on this. This could be a coincidence of course.

Did you add it?

**Comment by haziz-du** [comment]
> I was just surprised that suddenly, bitnami/cilium is appearing in our repository. It was after you worked on this. This could be a coincidence of course.
> 
> Did you add it?

as you can see in the Chart.yaml file that have dependencies, there is no` bitnami/cilium`,
https://github.com/programmfabrik/fylr-helm/blob/main/charts/fylr/Chart.yaml#L49

 also if I check the Postgres chart dependencies, the only chart I find is `common` chart see https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml

**Comment by haziz-du** [comment]
> At https://github.com/programmfabrik/fylr-helm/blob/main/charts/fylr/values.yaml#L637 you wrote:
> 
> ```
> postgresql:
>   enabled: false
>   image:
>     registry: docker.io
>     repository: bitnami/postgresql
>     tag: 16.3.0-debian-12-r18
>   postgresql:
>     auth:
>       username: "fylr"
>       password: "fylr"
>       database: "fylr"
> ```
> 
> But in my recent tests I had to use
> 
> ```
> postgresql:
>   enabled: false
>   image:
>     registry: docker.io
>     repository: bitnami/postgresql
>     tag: 16.3.0-debian-12-r18
>   auth:
>     username: "fylr"
>     password: "fylr"
>     database: "fylr"
> ```
> 
> Can you confirm that the current state of https://github.com/programmfabrik/fylr-helm/blob/main/charts/fylr/values.yaml is in error and correct it?

Both works,
right now this how I'm deploying fylr instance in the cloud, btw the `postgresPassword` should be set to avoid issues when upgrading, i'll add it

```
    postgresql:
      enabled: true
      postgresql:
        auth:
          postgresPassword: "HelloWorld2023"
          username: "fylr"
          password: "fylr"
          database: "fylr"
      auth:
        postgresPassword: "HelloWorld2023"
        username: "fylr"
        password: "fylr"
        database: "fylr"
```

**Comment by haziz-du** [comment]
Ok, changed

**Comment by KlausThornProgrammfabrik** [comment]
> Both works

For me, if I only use postgresql.auth, then it fails with ...
`Error: INSTALLATION FAILED: template: fylr/templates/secrets.yaml:14:22: executing "fylr/templates/secrets.yaml" at <index .Values "postgresql" "postgresql" "auth" "username">: error calling index: index of nil pointer`

If I only use postgresql.postgresql.auth, then it works.

So why should we ever use postgresql.auth? It looks confusing to have the values two times in values.yaml.

So I suggest to remove postgresql.auth and only have postgresql.postgresql.auth in https://github.com/programmfabrik/fylr-helm/blob/main/charts/fylr/values.yaml

**Comment by KlausThornProgrammfabrik** [comment]
hmm, wait, actually currently both are needed.

postgresql.postgresql.auth is needed to omit the error above

postgresql.auth is needed so that the password for role fylr is actually correct.

**Comment by KlausThornProgrammfabrik** [comment]
Jens-Thomas Hönow simplified the postgresql config in https://github.com/programmfabrik/fylr-helm/commit/dd5a94bec90141505ab5ba9f36e1ec5e958b571b
